name: posdelivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2

  # statemanagement
  get: 4.6.1
  # local storage_space:
  shared_preferences: ^2.0.8

  ## ui styling:
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  skeletons: ^0.0.3
  cached_network_image: ^3.1.0
  overlay_support: ^1.2.1
  flutter_smart_dialog: ^3.0.1
  pin_code_fields: ^7.3.0
  expandable: ^5.0.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  dropdown_search: ^2.0.1
  flutter_beep: ^1.0.0
  bluetooth_print: ^3.0.1
  image_utils_class: ^2.0.0
  blue_thermal_printer: ^1.1.8
  path_provider: ^2.0.8
  #image_picker_saver: ^0.3.0
  flutter_speed_dial: ^5.0.0+1
  skeleton_text: ^3.0.0
  audioplayers: ^0.20.1
  qr_code_scanner: ^0.6.1
  

 
  #app service
  package_info: ^2.0.2
  dio: ^4.0.1
  connectivity: ^3.0.6
  logging: ^0.11.3

  uuid: ^3.0.5
  flutter_slidable: ^0.5.4
  open_file: ^3.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/




  fonts:
    - family: DIN Next LT Arabic
      fonts:
        - asset: assets/fonts/ar/DINNextLTArabic-Regular.ttf
        - asset: assets/fonts/ar/DINNextLTArabic-Bold.ttf
    - family: Elysio
      fonts:
        - asset: assets/fonts/en/Elysio-Light.ttf
        - asset: assets/fonts/en/Elysio-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf