name: posdelivery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  geolocator: ^9.0.1
  file_picker:
  permission_handler: ^10.0.1
  flutter_pos_printer_platform: ^1.0.4
  flutter_esc_pos_utils: ^0.1.7
  printing: ^5.9.2
  pdf: ^3.8.2
  audioplayers: ^0.20.1
  auto_size_text: ^3.0.0
  blue_thermal_printer: ^1.2.0
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  dropdown_search: ^2.0.1
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_slidable: ^0.6.0
  flutter_smart_dialog: ^3.0.1
  flutter_speed_dial: ^5.0.0+1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  flutter_typeahead: ^3.2.4
  get: 4.6.1
  google_fonts: ^2.1.0
  image_utils_class: ^2.0.0
  intl: ^0.17.0
  logging: ^0.11.3
  open_file: ^3.2.1
  overlay_support: ^1.2.1
  package_info: ^2.0.2
  path_provider: ^2.0.8
  pin_code_fields: ^7.3.0
  qr_code_scanner: ^0.6.1
  shared_preferences: ^2.0.8
  skeleton_text: ^3.0.0
  skeletons: ^0.0.3
  textfield_search: ^0.10.0
  uuid: ^3.0.5
  sembast: ^3.2.0
  logger: ^1.1.0
  json_annotation: ^4.1.0
  searchfield: ^0.6.6
  flutter_switch: ^0.3.2
  flutter_advanced_switch: ^3.0.1
  font_awesome_flutter: ^10.1.0





dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/svg/


  fonts:
    - family: DIN Next LT Arabic
      fonts:
        - asset: assets/fonts/ar/DINNextLTArabic-Regular.ttf
        - asset: assets/fonts/ar/DINNextLTArabic-Bold.ttf
    - family: Elysio
      fonts:
        - asset: assets/fonts/en/Elysio-Light.ttf
        - asset: assets/fonts/en/Elysio-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
