class Rows {
  String? id;
  String? saleId;
  String? productId;
  String? productCode;
  String? productName;
  String? productType;
  String? optionId;
  String? netUnitPrice;
  String? unitPrice;
  String? quantity;
  String? warehouseId;
  String? itemTax;
  String? taxRateId;
  String? tax;
  String? discount;
  String? itemDiscount;
  String? subtotal;
  String? serialNo;
  String? realUnitPrice;
  String? saleItemId;
  String? productUnitId;
  String? productUnitCode;
  String? unitQuantity;
  String? comment;
  String? gst;
  String? cGst;
  String? sGst;
  String? iGst;
  String? taxCode;
  String? taxName;
  String? taxRate;
  String? variant;
  String? details;
  String? hsnCode;
  String? secondName;
  String? taxMethod;

  Rows.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    saleId = json['sale_id'];
    productId = json['product_id'];
    productCode = json['product_code'];
    productName = json['product_name'];
    productType = json['product_type'];
    optionId = json['option_id'];
    netUnitPrice = json['net_unit_price'];
    unitPrice = json['unit_price'];
    quantity = json['quantity'];
    warehouseId = json['warehouse_id'];
    itemTax = json['item_tax'];
    taxRateId = json['tax_rate_id'];
    tax = json['tax'];
    discount = json['discount'];
    itemDiscount = json['item_discount'];
    subtotal = json['subtotal'];
    serialNo = json['serial_no'];
    realUnitPrice = json['real_unit_price'];
    saleItemId = json['sale_item_id'];
    productUnitId = json['product_unit_id'];
    productUnitCode = json['product_unit_code'];
    unitQuantity = json['unit_quantity'];
    comment = json['comment'];
    gst = json['gst'];
    cGst = json['cgst'];
    sGst = json['sgst'];
    iGst = json['igst'];
    taxCode = json['tax_code'];
    taxName = json['tax_name'];
    taxRate = json['tax_rate'];
    variant = json['variant'];
    details = json['details'];
    hsnCode = json['hsn_code'];
    secondName = json['second_name'];
    taxMethod = json['tax_method'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['sale_id'] = saleId;
    data['product_id'] = productId;
    data['product_code'] = productCode;
    data['product_name'] = productName;
    data['product_type'] = productType;
    data['option_id'] = optionId;
    data['net_unit_price'] = netUnitPrice;
    data['unit_price'] = unitPrice;
    data['quantity'] = quantity;
    data['warehouse_id'] = warehouseId;
    data['item_tax'] = itemTax;
    data['tax_rate_id'] = taxRateId;
    data['tax'] = tax;
    data['discount'] = discount;
    data['item_discount'] = itemDiscount;
    data['subtotal'] = subtotal;
    data['serial_no'] = serialNo;
    data['real_unit_price'] = realUnitPrice;
    data['sale_item_id'] = saleItemId;
    data['product_unit_id'] = productUnitId;
    data['product_unit_code'] = productUnitCode;
    data['unit_quantity'] = unitQuantity;
    data['comment'] = comment;
    data['gst'] = gst;
    data['cgst'] = cGst;
    data['sgst'] = sGst;
    data['igst'] = iGst;
    data['tax_code'] = taxCode;
    data['tax_name'] = taxName;
    data['tax_rate'] = taxRate;
    data['variant'] = variant;
    data['details'] = details;
    data['hsn_code'] = hsnCode;
    data['second_name'] = secondName;
    data['tax_method'] = taxMethod;
    return data;
  }
}
